/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_tap;


import hola.Cita;
import hola.Persona;
import java.awt.Color;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author whois
 */
public class ClienteFrame extends javax.swing.JFrame {
//[85, 81]

    /**
     * Creates new form ClienteFrame
     */
    private Personaa cliente = new Personaa();
    private Personaa doctor = new Personaa();
    int indexC, indexD;
    private GridLayout grid = new GridLayout(1, 1);
    private ArrayList<Personaa> listPersonas = new ArrayList<>();
    private ArrayList<Citaa> citasReservadas = new ArrayList<>();

    public ClienteFrame() {
        initComponents();
        panelLista1.setLayout(grid);
        agregarcitabtn.setIcon(new ImageIcon("C:\\Users\\whois\\OneDrive\\Documentos\\NetBeansProject\\Proyecto_TAPPP\\src\\main\\java\\Imagenes\\muela-de-juicio (1).png"));
        combo();
        actualiza();
        JFrame IniciarsesionFrame = new JFrame();
        this.setLocationRelativeTo(null);

        IniciarsesionFrame.repaint();
        getContentPane().setBackground(Color.WHITE);
    }

    public ClienteFrame(Personaa cliente, int indexU, ArrayList<Personaa> listPersonas, ArrayList<Citaa> citasReservadas) {
        initComponents();
        panelLista1.setLayout(grid);
        this.indexC = indexU;
        this.cliente = cliente;
        this.listPersonas = listPersonas;
        this.citasReservadas=citasReservadas;
        agregarcitabtn.setIcon(new ImageIcon("C:\\Users\\whois\\OneDrive\\Documentos\\NetBeansProject\\Proyecto_TAP\\src\\main\\java\\Imagenes\\dental (1).png"));
        agregarcitabtn.setIcon(new ImageIcon("C:\\Users\\kenia\\OneDrive\\Documentos\\NetBeansProjects\\Proyecto_TAP\\src\\main\\java\\Imagenes\\muela-de-juicio (1).png"));
        combo();

        actualiza();
        this.setLocationRelativeTo(null);

        JFrame IniciarsesionFrame = new JFrame();

        IniciarsesionFrame.repaint();
        getContentPane().setBackground(new Color(180, 205, 230));
    }

    private void combo() {
        comboB.addItem("");
        for (int i = 0; i < listPersonas.size(); i++) {
            if (listPersonas.get(i).isDoctor()) {
                comboB.addItem(listPersonas.get(i).getNombre().toUpperCase() + " "
                        + listPersonas.get(i).getApellido().toUpperCase() + " (" + listPersonas.get(i).getUsuario() + ")");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCustom1 = new org.edisoncor.gui.label.LabelCustom();
        comboB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        agregarcitabtn = new org.edisoncor.gui.panel.PanelImage();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelLista1 = new javax.swing.JPanel();
        panel1 = new org.edisoncor.gui.panel.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelEspecialista = new javax.swing.JLabel();

        labelCustom1.setText("labelCustom1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        comboB.setBorder(null);
        comboB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboBMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Especialistas");

        jLabel3.setText("Agenda la cita");

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/header.png"))); // NOI18N
        panelImage1.setPreferredSize(new java.awt.Dimension(148, 64));

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );

        agregarcitabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregarCita.png"))); // NOI18N
        agregarcitabtn.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout agregarcitabtnLayout = new javax.swing.GroupLayout(agregarcitabtn);
        agregarcitabtn.setLayout(agregarcitabtnLayout);
        agregarcitabtnLayout.setHorizontalGroup(
            agregarcitabtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        agregarcitabtnLayout.setVerticalGroup(
            agregarcitabtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/backgroundListaCitas.png"))); // NOI18N

        jScrollPane1.setBorder(null);

        panelLista1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelLista1Layout = new javax.swing.GroupLayout(panelLista1);
        panelLista1.setLayout(panelLista1Layout);
        panelLista1Layout.setHorizontalGroup(
            panelLista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );
        panelLista1Layout.setVerticalGroup(
            panelLista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelLista1);

        panel1.setColorPrimario(new java.awt.Color(249, 250, 251));
        panel1.setColorSecundario(new java.awt.Color(249, 250, 251));
        panel1.setPreferredSize(new java.awt.Dimension(550, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(107, 114, 128));
        jLabel1.setText("Fecha");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(107, 114, 128));
        jLabel5.setText("Paciente");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(107, 114, 128));
        jLabel6.setText("Precio");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Historial de citas");

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelImage2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelEspecialista.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        labelEspecialista.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboB, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelEspecialista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(agregarcitabtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEspecialista))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(agregarcitabtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)))
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(panelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmar (){
                String nombreDoc = comboB.getSelectedItem().toString();
        labelEspecialista.setText(nombreDoc);
        String usuarioDoc2 = "", usuarioDoc = "";
        int i;
        System.out.println("nombre doc:" + nombreDoc);
        for (i = nombreDoc.length() - 1; i > 0; i--) {

            System.out.println("char: " + nombreDoc.charAt(i));
            if (nombreDoc.charAt(i) == '(') {
                break;
            }
            if (nombreDoc.charAt(i) != ')') {

                System.out.println("char: " + nombreDoc.charAt(i));

                usuarioDoc2 = usuarioDoc2 + nombreDoc.charAt(i);
            }

        }

        for (i = usuarioDoc2.length() - 1; i >= 0; i--) {
            //System.out.println("char: " + nombreDoc.charAt(i));

            usuarioDoc = usuarioDoc + usuarioDoc2.charAt(i);
        }

        //System.out.println("Usuario doc string: " + usuarioDoc);
        for (i = 0; i < listPersonas.size(); i++) {
            if (usuarioDoc.equals(listPersonas.get(i).getUsuario())) {
                doctor = listPersonas.get(i);
                indexD = i;
                break;
            }
        }
    }
    
    private void comboBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboBMouseClicked
        confirmar();
        actualiza();
    }//GEN-LAST:event_comboBMouseClicked

    private void actualiza() {
        int i, j = 0, filas = 0;
        Citaa cita;
        System.out.println("");

        panelLista1.removeAll();

        //for (i = 0; i < cliente.getCitasReservadas().size(); i++) {
        for (i = 0; i < citasReservadas.size(); i++) {
            if (citasReservadas.get(i).getCliente().equals(cliente)) {
                filas++;

            }
        }
        System.out.println("filas " + filas);
        grid.setRows(filas);
        System.out.println(cliente.getUsuario());

        for (i = 0; i < citasReservadas.size(); i++) {
            if (citasReservadas.get(i).getCliente().getUsuario().equals(cliente.getUsuario())) {
                cita = citasReservadas.get(i);
                PanelCitasCliente panelCitas = new PanelCitasCliente(cita);
                panelLista1.add(panelCitas);
            }
        }

        panelLista1.updateUI();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteFrame().setVisible(true);
            }
        });
    }

    public ArrayList<Personaa> getListPersonas() {
        return listPersonas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.panel.PanelImage agregarcitabtn;
    private javax.swing.JComboBox<String> comboB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.label.LabelCustom labelCustom1;
    private javax.swing.JLabel labelEspecialista;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private javax.swing.JPanel panelLista1;
    // End of variables declaration//GEN-END:variables
}
