/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_tap;


import hola.Cita;
import hola.Persona;
import java.awt.Color;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author whois
 */
public class RegistroPagoFrame extends javax.swing.JFrame {

    private boolean textF = false;
    private Citaa cita = new Citaa();
    private Personaa cliente;
    private Personaa doctor;
    private int indexCD, indexCC;
    ArrayList<Personaa> listPersonas = new ArrayList<>();
    ArrayList<Citaa> citasReservadas = new ArrayList<>();
    private JLabel label = new JLabel("Cita Pagada en su totalidad");
    private JTextField textField = new JTextField("");

    /**
     * Creates new form RegistroPagoFrame
     */
    public RegistroPagoFrame() {
        initComponents();
    }

    public RegistroPagoFrame(ArrayList<Personaa> listPersonas, Personaa cliente, Personaa doctor, int indexCD, Citaa cita, ArrayList<Citaa> citasReservadas) {
        initComponents();
        this.cita = cita;
        this.listPersonas = listPersonas;
        this.citasReservadas = citasReservadas;
        this.cliente = cliente;
        this.doctor = doctor;
        this.indexCD = indexCD;
        //llenar();

        for (int i = 0; i < citasReservadas.size(); i++) {
          if (citasReservadas.get(i).getCliente().equals(cliente.getNombre())) {
            if (cita == citasReservadas.get(i)) {
                indexCC = i;
                break;
            }
        }
        }
        // Establecer el layout manager
        //setLayout(new BoxLayout(this.getContentPane(), BoxLayout.Y_AXIS));

        // Actualizar el texto del JLabel jLabel2
        jLabel2.setText("$" + doctor.getCostoConsulta());
        if (cita.isCitaPagada()) {
            jLabel5.setText("$" + cita.getAvancePago());
        }
        jLabel5.setText("$" + cita.getAvancePago());

        // Comprobar si la cita está pagada
        if (cita.isCitaPagada()) {
            label.setBounds(195, 77, 250, 22);
            add(label);
        } else {
            textF = true;

            //textField.setSize(70, 22);
            textField.setBounds(195, 77, 70, 22);
            add(textField);
        }

        this.setLocationRelativeTo(null);
        JFrame IniciarsesionFrame = new JFrame();
        IniciarsesionFrame.repaint();
         getContentPane().setBackground(new Color(180, 205, 230));
    }

    public void llenar() {
        jLabel2.setText("$" + doctor.getCostoConsulta());
        if (cita.isCitaPagada()) {
            label.setText("Cita Pagada en su totalidad");
            label.setVisible(true);
            add(label);
        } else {
            textField.setText("");
            add(textField);

        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Costo total de cita:");

        jLabel2.setText("jLabel2");

        jLabel3.setText("Pago a realizar:");

        jLabel4.setText("Monto pagado:");

        jLabel5.setText("jLabel5");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))))
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(83, 83, 83)
                .addComponent(jButton1)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (textF) {
            int option = JOptionPane.showConfirmDialog(null, "¿Estás seguro de querer hacer esto?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {//confirmación de querer realizar los cambios
                System.out.println("Aceptamos");
                if (textField.getText() != null && !textField.getText().equals("")) {//checar que se haya metido algún valor

                    System.out.println("Llenamos el field");
                    try {//evita excepción de letras o caracteres 

                        int nuevoPago = Integer.parseInt(textField.getText());
                        nuevoPago = nuevoPago + cita.getAvancePago();
                        System.out.println("nuevo pago: " + nuevoPago);
                        if (nuevoPago <= doctor.getCostoConsulta() && nuevoPago > 0) {//checamos que no haya pagos negativos o mayores del monto
                            System.out.println("No hay pago negativo");
                            if (nuevoPago == doctor.getCostoConsulta()) {//checamos si ya se saldó por completo la consulta
                                System.out.println("Ya se pagó por completo");
                                cita.setCitaPagada(true);
                                System.out.println("entró a pago completado");
                                cita.setAvancePago(doctor.getCostoConsulta());
                                System.out.println("guardó pago completo");
                                textF = false;
                            } else {
                                System.out.println("Se abonó");
                                cita.setAvancePago(nuevoPago);
                            }
                            //citasReservadas.set(indexCD, cita);
                            //System.out.println("doc cool");
                            //cliente.getCitasReservadas().set(indexCC, cita);
                            //System.out.println("cliente cool");
                            actualizarArray();
                            System.out.println("GUARDADO");
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(null, "Revise el monto ingresado");
                        }
                        llenar();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Favor de ingresar solo números: "+e);
                    }
                }
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void actualizarArray() {
        int indexD = 0, indexC = 0;

        for (int i = 0; i < listPersonas.size(); i++) {
            if (doctor.getUsuario().equals(listPersonas.get(i).getUsuario())) {
                indexD = i;
            }
        }

        for (int i = 0; i < listPersonas.size(); i++) {
            if (cliente.getUsuario().equals(listPersonas.get(i).getUsuario())) {
                indexC = i;
            }
        }

        listPersonas.set(indexC, cliente);
        listPersonas.set(indexD, doctor);
    }

    public ArrayList<Personaa> getListPersonas() {
        return listPersonas;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPagoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPagoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPagoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPagoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPagoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
